name: Wipe repository (keep .github)

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  wipe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Delete everything except .github
        shell: bash
        run: |
          # 1) Remove all *tracked* files except those in .github/
          git ls-files -z | grep -vzE '^\.github/' | xargs -0 git rm -f

          # 2) Remove *untracked* files/directories in repo root,
          #    but spare .github/ and the .git repository directory
          find . -mindepth 1 -maxdepth 1 \
               ! -name '.github' \
               ! -name '.git' \
               -exec rm -rf {} +

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Delete repository content (except .github) via workflow-dispatch" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}