name: Wipe repository

# Manual trigger from GitHub iOS Shortcut
on:
  workflow_dispatch:   # ← no inputs – runs as soon as it’s dispatched

permissions:
  contents: write      # needed to push the “empty” commit
  actions: read

jobs:
  wipe:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the branch / ref specified in the dispatch call
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}   # uses the ref supplied by the dispatch event

      # 2. Delete everything except the .git directory
      - name: Delete repository content
        run: |
          git rm -rf .
          rm -rf ./* || true

      # 3. Commit & push the deletion
      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Delete repository content via workflow-dispatch" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}